name: Rollback A Change
on:
  workflow_dispatch:
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.24.0"
      - run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - run: goose status
        env:
          GOOSE_DRIVER: postgres
          GOOSE_MIGRATION_DIR: ./migrations/
          GOOSE_DBSTRING: ${{ secrets.GOOSE_DBSTRING }}
      - run: goose down
        env:
          GOOSE_DRIVER: postgres
          GOOSE_MIGRATION_DIR: ./migrations/
          GOOSE_DBSTRING: ${{ secrets.GOOSE_DBSTRING }}
