name: Validate Database Changes
on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ghcr.io/zmaillard/rsp.db:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: rsp
          POSTGRES_DB: roadsign
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.24.0"
      - run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - run: goose status
        env:
          GOOSE_DRIVER: postgres
          GOOSE_MIGRATION_DIR: ./migrations/
          GOOSE_DBSTRING: ${{ secrets.GOOSE_DBSTRING }}
      - run: goose validate
        env:
          GOOSE_DRIVER: postgres
          GOOSE_MIGRATION_DIR: ./migrations/
          GOOSE_DBSTRING: ${{ secrets.GOOSE_DBSTRING }}
